# Generated by Django 3.0.6 on 2020-06-13 20:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome', max_length=50, verbose_name='Nome')),
                ('status', models.BooleanField(verbose_name='Sataus')),
                ('env', models.CharField(help_text='Env.', max_length=20, verbose_name='Env')),
                ('version', models.CharField(help_text='Versão', max_length=5, verbose_name='Versão')),
                ('address', models.GenericIPAddressField(help_text='Endereço IPV4/IPV6', validators=[django.core.validators.validate_ipv46_address], verbose_name='Endereço')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome', max_length=50, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome', max_length=50, verbose_name='Nome')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Último Login')),
                ('email', models.EmailField(help_text='E-mail', max_length=255, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='E-mail')),
                ('password', models.CharField(help_text='Password', max_length=50, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='GroupUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Group')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('CRITICAL', 'CRITICAL'), ('DEBUG', 'DEBUG'), ('ERROR', 'ERROR'), ('WARNING', 'WARNING'), ('INFO', 'INFO')], help_text='Nível', max_length=20, verbose_name='Nível')),
                ('data', models.TextField(help_text='Observações', verbose_name='Informações')),
                ('arquivado', models.BooleanField(verbose_name='Arquivado')),
                ('date', models.DateField(help_text='Data', verbose_name='Data')),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Agent')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
    ]
