# Generated by Django 3.0.6 on 2020-06-13 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'verbose_name': 'Agente'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Evento'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Grupo'},
        ),
        migrations.AlterModelOptions(
            name='groupuser',
            options={'verbose_name': 'Grupo de usuário'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuário'},
        ),
    ]
