# Generated by Django 3.0.6 on 2020-06-13 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200613_2143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'verbose_name': 'Agente'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Evento'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Grupo'},
        ),
        migrations.AlterModelOptions(
            name='groupuser',
            options={'verbose_name': 'Grupo de Usuário'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuário'},
        ),
        migrations.AlterField(
            model_name='event',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Agent'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(help_text='Data', null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.User'),
        ),
        migrations.AlterField(
            model_name='groupuser',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Group'),
        ),
        migrations.AlterField(
            model_name='groupuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(auto_now=True, verbose_name='Último Login'),
        ),
    ]
