# Generated by Django 3.0.6 on 2020-06-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200613_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(help_text='Data', verbose_name='Data'),
        ),
    ]
